### ISSUE TITLE
Order product Status 

### ISSUE THREAD

**Issue by BonchayHi5** [selendra/albazaar-apps#11]
**### **<!-- Request order product status> @saingsab 

###User Story
-As a Seller when buyer ordered his product he cannot check the status of product .Example Is he(seller) already confirm the payment or shipment yet ?

-As a Buyer when seller confirm the payment and shippment ,buyer cannot track which process is his order product in.

## Problem 
-Unable to track process of product after it has been order****

**Comment by saingsab** [comment]
[x] Adding Order Status to Order list both seller/buyer.
