### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by DaveatCor** [selendra/albazaar-apps#20]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'body' was called on null.
E/flutter (21070): Receiver: null
E/flutter (21070): Tried calling: body
E/flutter (21070): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (21070): #1      SellerProvider.fetchBuyerOrder (package:selendra_marketplace_app/core/providers/seller_provider.dart:26:54)
E/flutter (21070): <asynchronous suspension>
E/flutter (21070): #2      AuthProvider.signInByEmail (package:selendra_marketplace_app/core/providers/auth_provider.dart:183:63)

**Comment by BonchayHi5** [comment]
Can you describe when does it appear this error? @DaveatCor

**Comment by BonchayHi5** [comment]
I already fixed it and push to dev please check if that error appear again or not @DaveatCor

**Comment by DaveatCor** [comment]
Add more try and catch inside Fetch Buyer Order
