### ISSUE TITLE
Make order endpoint

### ISSUE THREAD

**Issue by BonchayHi5** [selendra/albazaar-apps#6]
- [ ] make order endpoint is not working properly when we add new order it doesnt show up in order list

**Comment by saingsab** [comment]
@BonchayHi5 can you raise one issue one problem. it's easy to track.

**Comment by BonchayHi5** [comment]
> @BonchayHi5 can you raise one issue one problem. it's easy to track.

Yes,I will change it.

**Comment by saingsab** [comment]
**Scenario:** 
User A login and placing the order product, But the product doesn't list in order endpoint. 

**Issue:**
Product doesn't mark in order both buyer and seller.
