### ISSUE TITLE
List order endpoint

### ISSUE THREAD

**Issue by BonchayHi5** [selendra/albazaar-apps#8]
- [ ] add thumbnail and product image in list order(seller/ buyer) endpoints

**Comment by saingsab** [comment]
- adding thumbnail in the order endpoint.

**Comment by BonchayHi5** [comment]
> * adding thumbnail in the order endpoint.

and product name in order endpoint

**Comment by saingsab** [comment]
![image](https://user-images.githubusercontent.com/6874962/100320817-56387b80-2ff4-11eb-94e0-3ac56e88e73f.png)
above request has been deployed adding more information for buyer and seller like an attached image.
